spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev   # 开发环境
  application:
    name: microservicecloud-config-zwq-dev
---
spring:
  profiles: test    # 测试环境
  application:
    name: microservicecloud-config-zwq-test

# 请保存为 UTF-8格式=======> 非常重要